### ISSUE TITLE
add code columns to response

### ISSUE THREAD

**Issue by mAlxc** [vmarchaud/jsdoc-http-plugin#1]
Hy,
first time i post an isssue sorry if this doesn't gone here :/ 
I wan't to know if it's possible to add the 'http response code' columns into the response.

exemple:
name|tpye|description|code

by the way thank for the @response and @code :)

**Comment by vmarchaud** [comment]
i dont think its possible because jsdoc parse `@tag {type} name description` but i will checkout :)

**Comment by mAlxc** [comment]
thank you ^^
