### ISSUE TITLE
Get a directory=<directory> is mandatory

### ISSUE THREAD

**Issue by molinto** [vmarchaud/jsdoc-http-plugin#10]
Followed instructions 

jsdoc --config jsdoc.conf
An argument like -d=<directory> or --directory=<directory> is mandatory!
Try 'jsdoc --help' or 'man jsdoc' for more information.

**Comment by vmarchaud** [comment]
You need to the configure the directory where to lookup for docs either in the `.conf` or via the cli flags, not related to this project

**Comment by molinto** [comment]
Thanks, my bad.

I had to use _./node_modules/.bin/jsdoc -c jsdoc.conf_ to get around this.
