### ISSUE TITLE
Difference between the parameters & route params

### ISSUE THREAD

**Issue by molinto** [vmarchaud/jsdoc-http-plugin#13]
Both show, one with no Type

```
/**
 * @function remove
 * @name remove
 * @description blah blah
 * @path {DELETE} /abc/:id
 * @params {string} id Unique identifier
 * @header {string} Authorization JWT token
 * @header {string} Content-Type application/json
 * @auth restrictToRoles('superadmin')
 * @code {200} If the request is successful
 * @code {500} Issue with blah blah
 * @since 1.0.0
 * @response {Json} response In {@link Json} format
 * @response {Object} response.data Empty object
 */
```

![Selection_626](https://user-images.githubusercontent.com/279285/57458889-1111f480-726a-11e9-89e7-8acfe07c35c7.png)

Not sure if I'm doing something wrong

**Comment by vmarchaud** [comment]
The plugin will inject the `Route parameters` part in the doc but i believe the `Parameters` is injected by JSDoc itself. From what i red, the `params` property is already used internally so when i add mine, jsdoc believe it's his own and print it too. I don't think we have a way to remove it without renaming the `params` tag

**Comment by vmarchaud** [comment]
Actually someone (#11) already had the issue, closing this one
