### ISSUE TITLE
Add escaping for parameter type

### ISSUE THREAD

**Issue by Bitluck** [vmarchaud/jsdoc-http-plugin#15]
Bug with displaying array types, like:
```js
@body {string[]} body_string_params - Array of string params     
@body {Object[]} body_object_params - Array of object params
```
When an array is passed as a type, the angle brackets are perceived as part of the HTML document. In HTML, it looks like:
```html
<td class="type">
  Array.
  <object></object>
</td>
```
**Actual result**:
![image](https://user-images.githubusercontent.com/1412266/62007743-11d46b80-b173-11e9-990e-44f51d8f960f.png)
**Expected result**:
![image](https://user-images.githubusercontent.com/1412266/62007761-49431800-b173-11e9-824a-56ffda9b8bd5.png)

**Comment by vmarchaud** [comment]
Thanks a lot for making a PR for that ! I've published the version `0.3.1` with your fix.
