### ISSUE TITLE
Params Not Being Documented for Express Endpoints

### ISSUE THREAD

**Issue by SudoZachCampbell** [vmarchaud/jsdoc-http-plugin#17]
Having an issue when @params are not showing in the following Express code:
```javascript
/** Get object by ID endpoint
 * 
 * @name Fields by ID
 * @memberof Field APIs
 * @path {GET} /fields/:objectId
 * @params {String} :objectId is the Field ID to search by
 */
router.get('/:objectId', (req, res, next) => {
  fieldsSvc.getItem(req.params.objectId, 'Fields').then((data) => {
    res.json(data);
  }).catch(next);
});
```
I tried removing the namespace to see if it was affecting it but no change.

**Comment by vmarchaud** [comment]
Could you share what does it show when exporting it ?

**Comment by SudoZachCampbell** [comment]
![image](https://user-images.githubusercontent.com/52421803/67307244-1b5e3d00-f4f0-11e9-964a-0bc443be62a8.png)

**Comment by SudoZachCampbell** [comment]
Resolved the issue, in the plugins section in my jsdoc config I had to put "node_modules/jsdoc-http-plugin". Could possibly be due to the location of the jsdoc config file inside a "config" directory, however in that case I thought the fix would be "../node_modules/jsdoc-http-plugin"
