### ISSUE TITLE
@param

### ISSUE THREAD

**Issue by mAlxc** [vmarchaud/jsdoc-http-plugin#2]
the @param tag is already use by jsdoc and the addition of your plugin replace the name of @param  for method.

**Comment by mAlxc** [comment]
Sorry i made a mistake he add your routes parameters to the method parameters

![image](https://cloud.githubusercontent.com/assets/15339179/26731139/5e486402-47b3-11e7-88c3-5d701efb65d3.png)

**Comment by vmarchaud** [comment]
My tag is @params exactly for this reason

**Comment by mAlxc** [comment]
I know but this 
![image](https://cloud.githubusercontent.com/assets/15339179/26731611/e93d8424-47b4-11e7-9d51-725bfe1a3016.png)

produce this : 
![image](https://cloud.githubusercontent.com/assets/15339179/26731696/23fc668e-47b5-11e7-9d74-ec63db40ad27.png)

and your the only plugin i have on this one ;)
