### ISSUE TITLE
Undefined when description is missing

### ISSUE THREAD

**Issue by ertrzyiks** [vmarchaud/jsdoc-http-plugin#3]
When we don't have any description, documention includes `undefined` text.

<img width="467" alt="screenshot 2017-09-19 20 41 33" src="https://user-images.githubusercontent.com/2437969/30609183-f7961204-9d7a-11e7-9cfb-40f9d069db77.png">

What do you think about replacing `${e.doclet.description}` with `${e.doclet.description || ''}`?

**Comment by vmarchaud** [comment]
Good catch, if you can make a PR for this, i'll merge this ASAP :)

**Comment by vmarchaud** [comment]
I will review all the PRs tomorrow (was busy at work today), or in worst case this weekend :)
